version: "3.8"

services:
  adventure:
    image: adventure-image
    build: .
    networks:
      - adventure-mysql
    depends_on:
      mysqldb:
        condition: service_healthy
    ports:
      - "8080:8080"

  mysqldb:
    container_name: adventure-db
    image: mysql:8
    networks:
      - adventure-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=2846
      - MYSQL_DATABASE=adventure
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

networks:
  adventure-mysql: